export const CATEGORIES = [
    { id: 9, name: 'General Knowledge', fontAwesomeIcon: 'brain' },
    { id: 10, name: 'Entertainment: Books', fontAwesomeIcon: 'book' },
    { id: 11, name: 'Entertainment: Films', fontAwesomeIcon: 'film' },
    { id: 12, name: 'Entertainment: Music', fontAwesomeIcon: 'music' },
    { id: 13, name: 'Entertainment: Musicals & Theatres', fontAwesomeIcon: 'masks-theater' },
    { id: 14, name: 'Entertainment: TV', fontAwesomeIcon: 'tv' },
    { id: 15, name: 'Entertainment: Video Games', fontAwesomeIcon: 'gamepad' },
    { id: 16, name: 'Entertainment: Board Games', fontAwesomeIcon: 'chess' },
    { id: 17, name: 'Science & Nature', fontAwesomeIcon: 'leaf' },
    { id: 18, name: 'Science: Computers', fontAwesomeIcon: 'laptop-code' },
    { id: 19, name: 'Science: Mathematics', fontAwesomeIcon: 'calculator' },
    { id: 20, name: 'Mythology', fontAwesomeIcon: 'ankh' },
    { id: 21, name: 'Sports', fontAwesomeIcon: 'futbol' },
    { id: 22, name: 'Geography', fontAwesomeIcon: 'earth-europe' },
    { id: 23, name: 'History', fontAwesomeIcon: 'fort-awesome' },
    { id: 24, name: 'Politics', fontAwesomeIcon: 'landmark-flag' },
    { id: 25, name: 'Art', fontAwesomeIcon: 'palette' },
    { id: 26, name: 'Celebrities', fontAwesomeIcon: 'star' },
    { id: 27, name: 'Animals', fontAwesomeIcon: 'paw' },
    { id: 28, name: 'Vehicles', fontAwesomeIcon: 'car' },
    { id: 30, name: 'Science: Gadgets', fontAwesomeIcon: 'walkie-talkie' },
    { id: 31, name: 'Entertainment: Anime & Manga', fontAwesomeIcon: 'dragon' },
    { id: 32, name: 'Entertainment: Cartoons & Animations', fontAwesomeIcon: 'tv' },
];
